// AUTO-GENERATED by build.py from GLOBAL_FAQS / ROUTES / TAXI_SERVICES /
// SIGHTSEEING_PLACES / HOTEL_CATEGORIES / VEHICLES / PACKAGE_DESTINATIONS.
// Do not hand-edit — edit the source lists in build.py and re-run it.
var AGENT_DATA = {
  "whatsappNumber": "919103331334",
  "phone": "9103331334",
  "phone2": "8493988568",
  "businessName": "Patnitop Travels Hub",
  "routes": [
    {
      "id": "katra",
      "label": "Katra to Patnitop",
      "path": "katra-to-patnitop-taxi.html",
      "summary": "Patnitop Travels Hub arranges taxi service between Katra and Patnitop, including pickup from Katra Railway Station and drop directly at your Patnitop hotel.",
      "defaultPickup": "Katra town or Katra Railway Station",
      "defaultDrop": "Patnitop (your hotel)",
      "askSightseeing": true,
      "askHotel": true,
      "faqs": [
        {
          "q": "How far is Patnitop from Katra?",
          "a": "The exact travel time depends on road and weather conditions on the day \u2014 call us and we can advise based on current conditions."
        },
        {
          "q": "Can you pick us up from Katra Railway Station?",
          "a": "Yes, we provide Katra Railway Station pickup and drop as part of this route."
        },
        {
          "q": "Is a round trip available, or only one-way drop?",
          "a": "Both one-way taxi drop and full round-trip taxi service are available for Katra to Patnitop."
        }
      ]
    },
    {
      "id": "jammu",
      "label": "Jammu to Patnitop",
      "path": "jammu-to-patnitop-taxi.html",
      "summary": "Patnitop Travels Hub provides taxi service between Jammu and Patnitop, including pickup from Jammu Airport and Jammu Railway Station.",
      "defaultPickup": "Jammu (Airport / Railway Station / city)",
      "defaultDrop": "Patnitop (your hotel)",
      "askSightseeing": true,
      "askHotel": true,
      "faqs": [
        {
          "q": "Do you provide Jammu Airport pickup for Patnitop?",
          "a": "Yes, we offer Jammu Airport pickup and drop with onward taxi service to Patnitop."
        },
        {
          "q": "Do you provide Jammu Railway Station pickup?",
          "a": "Yes, Jammu Railway Station pickup and drop is available as part of this route."
        },
        {
          "q": "Can I book a one-way taxi from Jammu to Patnitop?",
          "a": "Yes, one-way taxi drop is available, along with full round-trip service if you need a return journey."
        }
      ]
    },
    {
      "id": "airport-railway",
      "label": "Airport / Railway Station Transfer",
      "path": "airport-railway-transfer.html",
      "summary": "Patnitop Travels Hub provides taxi pickup and drop at Jammu Airport, Jammu Railway Station and Katra Railway Station, with onward transfer to Patnitop, Katra or other Jammu & Kashmir destinations.",
      "defaultPickup": "Jammu Airport / Jammu Railway Station / Katra Railway Station",
      "defaultDrop": "Patnitop or your onward destination",
      "askSightseeing": false,
      "askHotel": true,
      "faqs": [
        {
          "q": "Which airport and railway stations do you cover?",
          "a": "We cover Jammu Airport, Jammu Railway Station and Katra Railway Station, with onward taxi transfer to Patnitop and nearby destinations."
        },
        {
          "q": "Should I share my flight or train number?",
          "a": "Yes, sharing your flight or train details and expected arrival time helps us plan your pickup accurately."
        }
      ]
    },
    {
      "id": "nathatop-sanasar",
      "label": "Nathatop & Sanasar Sightseeing",
      "path": "nathatop-sanasar-taxi.html",
      "summary": "Nathatop and Sanasar are two of the most visited viewpoints near Patnitop, and Patnitop Travels Hub arranges local taxi service to both.",
      "defaultPickup": "Your Patnitop hotel",
      "defaultDrop": "Nathatop & Sanasar (return to Patnitop)",
      "askSightseeing": false,
      "askHotel": false,
      "faqs": [
        {
          "q": "Can Nathatop and Sanasar be covered in one day?",
          "a": "Depending on your schedule and road conditions on the day, both can often be combined \u2014 call us and we will help plan the timing."
        },
        {
          "q": "Do you provide a driver-guide for sightseeing?",
          "a": "Our drivers are familiar with these local routes; for detailed historical or cultural guiding, let us know in advance so we can advise what is available."
        }
      ]
    },
    {
      "id": "srinagar",
      "label": "Srinagar Taxi",
      "path": "srinagar-taxi.html",
      "summary": "Patnitop Travels Hub can arrange outstation taxi service to Srinagar from Patnitop or Jammu, as part of a wider Jammu & Kashmir trip.",
      "defaultPickup": "Patnitop or Jammu",
      "defaultDrop": "Srinagar",
      "askSightseeing": true,
      "askHotel": true,
      "faqs": [
        {
          "q": "Do you provide taxi service all the way to Srinagar?",
          "a": "Yes, subject to availability, we can arrange taxi service to Srinagar from Patnitop or Jammu."
        },
        {
          "q": "Can this be combined with Gulmarg or Pahalgam?",
          "a": "Yes, this can be arranged as part of a wider Jammu & Kashmir tour \u2014 see our tour packages page for more."
        }
      ]
    },
    {
      "id": "bhaderwah",
      "label": "Bhaderwah Taxi",
      "path": "bhaderwah-taxi.html",
      "summary": "Patnitop Travels Hub arranges taxi service to Bhaderwah, known as \"Mini Kashmir\", from Patnitop and Jammu.",
      "defaultPickup": "Patnitop or Jammu",
      "defaultDrop": "Bhaderwah",
      "askSightseeing": true,
      "askHotel": true,
      "faqs": [
        {
          "q": "How do I book a Bhaderwah taxi?",
          "a": "Call or WhatsApp 9103331334, or use the booking form on this website with your travel dates."
        },
        {
          "q": "Can I combine Bhaderwah with a Patnitop trip?",
          "a": "Yes, this route is often combined with a Patnitop or wider Jammu & Kashmir itinerary \u2014 call us to plan it."
        }
      ]
    }
  ],
  "taxiServices": [
    {
      "name": "Katra to Patnitop Taxi",
      "desc": "Pickup from Katra town or Katra Railway Station, direct to Patnitop."
    },
    {
      "name": "Jammu to Patnitop Taxi",
      "desc": "Jammu Airport or Jammu Railway Station to Patnitop, one-way or round trip."
    },
    {
      "name": "Airport & Railway Station Transfers",
      "desc": "Jammu Airport, Jammu Railway Station, Katra Railway Station pickup &amp; drop."
    },
    {
      "name": "Patnitop Sightseeing Taxi",
      "desc": "Local taxi for Nathatop, Sanasar and nearby attractions."
    },
    {
      "name": "Nathatop & Sanasar Taxi",
      "desc": "Dedicated taxi service for the Nathatop and Sanasar viewpoints."
    },
    {
      "name": "Srinagar Taxi",
      "desc": "Taxi service from Patnitop or Jammu towards Srinagar."
    },
    {
      "name": "Bhaderwah Taxi",
      "desc": "Taxi service to Bhaderwah from Patnitop and Jammu."
    },
    {
      "name": "Hotel Pickup & Drop",
      "desc": "Pickup and drop from your Patnitop hotel for onward travel."
    }
  ],
  "sightseeing": [
    {
      "name": "Nathatop",
      "desc": "A panoramic viewpoint above Patnitop, popular for mountain views."
    },
    {
      "name": "Sanasar",
      "desc": "A bowl-shaped meadow valley, a short taxi ride from Patnitop."
    },
    {
      "name": "Patnitop Meadows",
      "desc": "The open grassland at the centre of Patnitop town."
    },
    {
      "name": "Naag Temple",
      "desc": "A local temple site near Patnitop."
    },
    {
      "name": "Padora Park",
      "desc": "A local park area in the Patnitop region."
    },
    {
      "name": "Children Park",
      "desc": "A family-friendly park in Patnitop."
    },
    {
      "name": "Shiv Temple",
      "desc": "A local temple, easily combined with other nearby stops."
    }
  ],
  "hotelCategories": [
    {
      "name": "Budget Hotels",
      "desc": "Simple, comfortable stays for cost-conscious travellers."
    },
    {
      "name": "Family Hotels",
      "desc": "Rooms and layouts suited to families travelling together."
    },
    {
      "name": "Premium Hotels",
      "desc": "Higher-comfort stays for a more relaxed trip."
    }
  ],
  "vehicles": [
    {
      "name": "Dzire",
      "desc": "Compact sedan, suited to small families of up to 4 passengers with regular luggage."
    },
    {
      "name": "Ertiga",
      "desc": "MPV with more space, suited to 6 passengers with luggage."
    },
    {
      "name": "Innova / Toyota Crysta",
      "desc": "Comfortable SUV, a common choice for mountain routes, 6-7 passengers."
    },
    {
      "name": "Tempo Traveller",
      "desc": "Larger vehicle for groups and bigger families travelling together."
    }
  ],
  "packageDestinations": [
    "Patnitop",
    "Katra",
    "Jammu",
    "Bhaderwah",
    "Srinagar",
    "Gulmarg",
    "Pahalgam",
    "Sonamarg",
    "Doodhpathri",
    "Yusmarg"
  ],
  "faqs": [
    {
      "q": "How can I book a taxi in Patnitop?",
      "a": "Call or WhatsApp Dileep Singh at 9103331334, or fill in the booking form on this website with your pickup, drop, date and vehicle preference. We will confirm your taxi booking directly."
    },
    {
      "q": "Do you provide Katra to Patnitop taxi service?",
      "a": "Yes, Patnitop Travels Hub provides Katra to Patnitop taxi service and Patnitop to Katra taxi service, including pickup from Katra Railway Station."
    },
    {
      "q": "Do you provide Jammu Airport pickup?",
      "a": "Yes, we offer Jammu Airport pickup and drop, as well as Jammu Railway Station pickup and drop, connecting onward to Patnitop and other destinations."
    },
    {
      "q": "Can you arrange hotels in Patnitop?",
      "a": "Yes, we assist tourists with hotel booking in Patnitop across budget, family and premium categories, and can arrange combined hotel plus taxi packages."
    },
    {
      "q": "Do you provide Patnitop sightseeing?",
      "a": "Yes, we provide local sightseeing taxi service covering Patnitop, Nathatop, Sanasar and nearby attractions."
    },
    {
      "q": "Can I hire a taxi for Srinagar or Bhaderwah?",
      "a": "Yes, our team can arrange taxi and travel assistance to Srinagar, Bhaderwah, Gulmarg, Pahalgam, Sonamarg and other destinations across Jammu & Kashmir, subject to availability."
    },
    {
      "q": "Do you provide Tempo Traveller?",
      "a": "Yes, Tempo Traveller service is available for group and family travel. Call us to check current availability and fare."
    },
    {
      "q": "How can I contact Dileep Singh?",
      "a": "You can call or WhatsApp Dileep Singh at 9103331334 (alternate number 8493988568) or email singhdileep257@gmail.com."
    }
  ]
};
