// Patnitop Travels Hub — AI Agent (v1)
// Fully client-side, rule-based / button-driven assistant.
// No external API calls, no backend, no API keys, no paid service.
// Knowledge comes only from window.AGENT_DATA (see js/agent-data.js,
// generated by build.py from the same content already on the pages).
//
// The agent NEVER invents availability, prices, drivers, or bookings —
// every fact it states comes from AGENT_DATA; every enquiry ends by
// handing off to a real wa.me link, same as the rest of the site.

(function () {
  'use strict';
  if (typeof AGENT_DATA === 'undefined') return; // fail silently, rest of site unaffected

  var WA_NUMBER = AGENT_DATA.whatsappNumber;
  var PHONE = AGENT_DATA.phone;

  function waLink(message) {
    return 'https://wa.me/' + WA_NUMBER + '?text=' + encodeURIComponent(message);
  }

  // ---------------------------------------------------------------
  // Widget DOM — built once, injected at the end of <body>
  // ---------------------------------------------------------------
  var root = document.createElement('div');
  root.id = 'ptv-agent-root';

  root.innerHTML =
    '<button id="ptv-agent-launcher" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="ptv-agent-panel" aria-label="Open chat assistant">' +
      '<span class="ptv-agent-launcher-icon" aria-hidden="true">💬</span>' +
    '</button>' +
    '<div id="ptv-agent-panel" role="dialog" aria-modal="false" aria-label="Patnitop Travels Hub assistant" hidden>' +
      '<div class="ptv-agent-header">' +
        '<span class="ptv-agent-title">Patnitop Travels Hub</span>' +
        '<button id="ptv-agent-close" type="button" aria-label="Close chat">&times;</button>' +
      '</div>' +
      '<div class="ptv-agent-body" id="ptv-agent-body"></div>' +
      '<div class="ptv-agent-footer">' +
        '<a id="ptv-agent-wa-persistent" class="btn btn-whatsapp ptv-agent-wa-small" href="' + waLink('Hello Patnitop Travels Hub, I would like to enquire about a taxi/hotel booking.') + '" target="_blank" rel="noopener">💬 Chat on WhatsApp</a>' +
      '</div>' +
    '</div>';

  document.body.appendChild(root);

  var launcher = document.getElementById('ptv-agent-launcher');
  var panel = document.getElementById('ptv-agent-panel');
  var body = document.getElementById('ptv-agent-body');
  var closeBtn = document.getElementById('ptv-agent-close');

  // ---------------------------------------------------------------
  // Open / close
  // ---------------------------------------------------------------
  var opened = false;

  function openPanel() {
    panel.hidden = false;
    launcher.setAttribute('aria-expanded', 'true');
    if (!opened) {
      opened = true;
      renderGreeting();
    }
    closeBtn.focus();
  }

  function closePanel() {
    panel.hidden = true;
    launcher.setAttribute('aria-expanded', 'false');
    launcher.focus();
  }

  launcher.addEventListener('click', function () {
    if (panel.hidden) openPanel(); else closePanel();
  });
  closeBtn.addEventListener('click', closePanel);

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && !panel.hidden) closePanel();
  });

  // ---------------------------------------------------------------
  // Rendering helpers
  // ---------------------------------------------------------------
  function el(tag, cls, html) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html !== undefined) e.innerHTML = html;
    return e;
  }

  function clearBody() { body.innerHTML = ''; }

  function addBotMessage(html) {
    var msg = el('div', 'ptv-msg ptv-msg-bot', html);
    body.appendChild(msg);
    body.scrollTop = body.scrollHeight;
  }

  function addUserMessage(text) {
    var msg = el('div', 'ptv-msg ptv-msg-user');
    msg.textContent = text;
    body.appendChild(msg);
    body.scrollTop = body.scrollHeight;
  }

  // A row of quick-reply buttons. options = [{label, onClick}]
  function addButtons(options) {
    var wrap = el('div', 'ptv-btn-row');
    options.forEach(function (opt) {
      var b = document.createElement('button');
      b.type = 'button';
      b.className = 'ptv-choice-btn';
      b.textContent = opt.label;
      b.addEventListener('click', function () {
        addUserMessage(opt.label);
        wrap.querySelectorAll('button').forEach(function (btn) { btn.disabled = true; });
        opt.onClick();
      });
      wrap.appendChild(b);
    });
    body.appendChild(wrap);
    body.scrollTop = body.scrollHeight;
    return wrap;
  }

  // A single text/number/date input with a submit button.
  function addInput(opts) {
    var wrap = el('div', 'ptv-input-row');
    var input = document.createElement('input');
    input.type = opts.type || 'text';
    input.placeholder = opts.placeholder || '';
    input.setAttribute('aria-label', opts.placeholder || 'Your answer');
    if (opts.min) input.min = opts.min;
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'ptv-choice-btn ptv-input-submit';
    btn.textContent = 'Next →';

    function submit() {
      var val = input.value.trim();
      if (!val) { input.focus(); return; }
      addUserMessage(val);
      input.disabled = true;
      btn.disabled = true;
      opts.onSubmit(val);
    }
    btn.addEventListener('click', submit);
    input.addEventListener('keydown', function (e) { if (e.key === 'Enter') submit(); });

    wrap.appendChild(input);
    wrap.appendChild(btn);
    body.appendChild(wrap);
    body.scrollTop = body.scrollHeight;
    setTimeout(function () { input.focus(); }, 50);
    return wrap;
  }

  function backToMenuButton() {
    addButtons([{ label: '⬅ Main Menu', onClick: renderMainMenu }]);
  }

  function whatsAppFallback(message) {
    var link = el('a', 'btn btn-whatsapp ptv-inline-wa', '💬 Continue on WhatsApp');
    link.href = waLink(message);
    link.target = '_blank';
    link.rel = 'noopener';
    body.appendChild(link);
    body.scrollTop = body.scrollHeight;
  }

  // ---------------------------------------------------------------
  // Greeting + main menu
  // ---------------------------------------------------------------
  function renderGreeting() {
    clearBody();
    addBotMessage('Hi! 👋 Welcome to Patnitop Travels Hub. How can I help you?');
    renderMainMenuButtonsOnly();
  }

  function renderMainMenu() {
    addBotMessage('What would you like to do?');
    renderMainMenuButtonsOnly();
  }

  function renderMainMenuButtonsOnly() {
    addButtons([
      { label: '🚕 Book a Taxi', onClick: renderTaxiMenu },
      { label: '🏔️ Patnitop Sightseeing', onClick: renderSightseeing },
      { label: '🏨 Hotel Booking', onClick: renderHotels },
      { label: '📦 Tour Packages', onClick: renderPackages },
      { label: '🚗 Vehicles', onClick: renderVehicles },
      { label: '❓ FAQs', onClick: renderFaqMenu },
      { label: '💬 Chat on WhatsApp', onClick: function () {
          addBotMessage('Sure — tap below to continue on WhatsApp.');
          whatsAppFallback('Hello Patnitop Travels Hub, I would like to enquire about a taxi/hotel booking.');
          backToMenuButton();
        } },
    ]);
  }

  // ---------------------------------------------------------------
  // Taxi menu → route selection → booking flow
  // ---------------------------------------------------------------
  function renderTaxiMenu() {
    addBotMessage('Which taxi service do you need?');
    var opts = AGENT_DATA.routes.map(function (r) {
      return { label: r.label, onClick: function () { renderRouteInfo(r); } };
    });
    opts.push({ label: '⬅ Main Menu', onClick: renderMainMenu });
    addButtons(opts);
  }

  function renderRouteInfo(route) {
    addBotMessage('<strong>' + route.label + '</strong><br>' + route.summary);
    addButtons([
      { label: '📝 Start Enquiry', onClick: function () { startBookingFlow(route); } },
      { label: '⬅ Back to Taxi Options', onClick: renderTaxiMenu },
    ]);
  }

  // Generic booking flow, used for route-based taxi enquiries AND
  // (with a synthetic "route") for sightseeing/hotel/package/vehicle enquiries.
  function startBookingFlow(route) {
    var answers = { service: route.label };
    addBotMessage("Great — let's get a few details for your " + route.label + ' enquiry.');

    function askName() {
      addBotMessage('What name should I note down?');
      addInput({ placeholder: 'Your name', onSubmit: function (v) { answers.name = v; askDate(); } });
    }
    function askDate() {
      addBotMessage('What is your travel date?');
      addInput({ type: 'date', placeholder: 'Travel date', onSubmit: function (v) { answers.date = v; askPickup(); } });
    }
    function askPickup() {
      var hint = route.defaultPickup ? ' (e.g. ' + route.defaultPickup + ')' : '';
      addBotMessage('Pickup location?' + hint);
      addInput({ placeholder: 'Pickup location', onSubmit: function (v) { answers.pickup = v; askDrop(); } });
    }
    function askDrop() {
      var hint = route.defaultDrop ? ' (e.g. ' + route.defaultDrop + ')' : '';
      addBotMessage('Drop location?' + hint);
      addInput({ placeholder: 'Drop location', onSubmit: function (v) { answers.drop = v; askPassengers(); } });
    }
    function askPassengers() {
      addBotMessage('How many passengers?');
      addInput({ type: 'number', min: '1', placeholder: 'Number of passengers', onSubmit: function (v) { answers.passengers = v; askVehicle(); } });
    }
    function askVehicle() {
      addBotMessage('Any vehicle preference?');
      var opts = AGENT_DATA.vehicles.map(function (v) {
        return { label: v.name, onClick: function () { answers.vehicle = v.name; afterVehicle(); } };
      });
      opts.push({ label: 'Not sure — please suggest', onClick: function () { answers.vehicle = 'Not sure — please suggest'; afterVehicle(); } });
      addButtons(opts);
    }
    function afterVehicle() {
      if (route.askSightseeing) { askSightseeing(); }
      else if (route.askHotel) { askHotel(); }
      else { finish(); }
    }
    function askSightseeing() {
      addBotMessage('Would you like local sightseeing added to this trip?');
      addButtons([
        { label: 'Yes', onClick: function () { answers.sightseeing = 'Yes'; if (route.askHotel) { askHotel(); } else { finish(); } } },
        { label: 'No', onClick: function () { answers.sightseeing = 'No'; if (route.askHotel) { askHotel(); } else { finish(); } } },
      ]);
    }
    function askHotel() {
      addBotMessage('Do you need help with hotel booking in Patnitop too?');
      addButtons([
        { label: 'Yes', onClick: function () { answers.hotel = 'Yes'; finish(); } },
        { label: 'No', onClick: function () { answers.hotel = 'No'; finish(); } },
      ]);
    }
    function finish() { renderSummary(answers); }

    askName();
  }

  // A lighter enquiry flow for non-route topics (sightseeing / hotel /
  // package / vehicle general enquiries) — fewer, more relevant fields.
  function startSimpleEnquiry(serviceLabel, opts) {
    opts = opts || {};
    var answers = { service: serviceLabel };
    addBotMessage("Let's note a few details for your " + serviceLabel + ' enquiry.');

    function askName() {
      addBotMessage('What name should I note down?');
      addInput({ placeholder: 'Your name', onSubmit: function (v) { answers.name = v; askDate(); } });
    }
    function askDate() {
      addBotMessage('What date are you planning this for?');
      addInput({ type: 'date', placeholder: 'Date', onSubmit: function (v) { answers.date = v; askPassengers(); } });
    }
    function askPassengers() {
      addBotMessage('How many people is this for?');
      addInput({ type: 'number', min: '1', placeholder: 'Number of people', onSubmit: function (v) { answers.passengers = v; askNote(); } });
    }
    function askNote() {
      addBotMessage(opts.noteQuestion || 'Anything specific you would like us to know? (or type "none")');
      addInput({ placeholder: 'Details', onSubmit: function (v) { answers.note = v; renderSummary(answers); } });
    }
    askName();
  }

  // ---------------------------------------------------------------
  // Summary + WhatsApp handoff
  // ---------------------------------------------------------------
  function renderSummary(answers) {
    var rows = '';
    var order = ['service', 'name', 'date', 'pickup', 'drop', 'passengers', 'vehicle', 'sightseeing', 'hotel', 'note'];
    var labels = { service: 'Service', name: 'Name', date: 'Date', pickup: 'Pickup', drop: 'Drop', passengers: 'Passengers', vehicle: 'Vehicle', sightseeing: 'Sightseeing', hotel: 'Hotel required', note: 'Notes' };
    order.forEach(function (k) {
      if (answers[k]) rows += '<div class="ptv-summary-row"><span>' + labels[k] + '</span><strong>' + escapeHtml(answers[k]) + '</strong></div>';
    });

    addBotMessage('<div class="ptv-summary-card"><div class="ptv-summary-title">Your enquiry summary</div>' + rows + '</div>');
    addBotMessage('This is not a confirmed booking — vehicle and hotel availability, and the exact fare, are confirmed directly on WhatsApp with Dileep Singh.');

    var msgLines = ['New enquiry — Patnitop Travels Hub (via website assistant)'];
    order.forEach(function (k) {
      if (answers[k]) msgLines.push(labels[k] + ': ' + answers[k]);
    });
    var message = msgLines.join('\n');

    var link = el('a', 'btn btn-whatsapp ptv-inline-wa', '💬 Continue on WhatsApp');
    link.href = waLink(message);
    link.target = '_blank';
    link.rel = 'noopener';
    body.appendChild(link);
    body.scrollTop = body.scrollHeight;

    addButtons([{ label: '🔄 Start Over', onClick: renderMainMenu }]);
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c];
    });
  }

  // ---------------------------------------------------------------
  // Sightseeing / Hotels / Packages / Vehicles menus
  // ---------------------------------------------------------------
  function renderSightseeing() {
    var html = '<strong>Patnitop Sightseeing</strong><br>Places we cover:<ul class="ptv-list">';
    AGENT_DATA.sightseeing.forEach(function (p) { html += '<li><strong>' + p.name + '</strong> — ' + p.desc + '</li>'; });
    html += '</ul><p class="ptv-note">Opening hours and entry fees can change — please confirm current details with us.</p>';
    addBotMessage(html);
    addButtons([
      { label: '📝 Start Sightseeing Enquiry', onClick: function () {
          startSimpleEnquiry('Patnitop Sightseeing', { noteQuestion: 'Which places would you like to cover? (or type "not sure")' });
        } },
      { label: '⬅ Main Menu', onClick: renderMainMenu },
    ]);
  }

  function renderHotels() {
    var html = '<strong>Hotel Booking in Patnitop</strong><br>Categories we help with:<ul class="ptv-list">';
    AGENT_DATA.hotelCategories.forEach(function (h) { html += '<li><strong>' + h.name + '</strong> — ' + h.desc + '</li>'; });
    html += '</ul><p class="ptv-note">We do not confirm hotel availability here — that is checked directly on WhatsApp for your dates.</p>';
    addBotMessage(html);
    addButtons([
      { label: '📝 Start Hotel Enquiry', onClick: function () {
          startSimpleEnquiry('Hotel Booking', { noteQuestion: 'What budget category and any preferences? (or type "not sure")' });
        } },
      { label: '⬅ Main Menu', onClick: renderMainMenu },
    ]);
  }

  function renderPackages() {
    var html = '<strong>Jammu &amp; Kashmir Tour Packages</strong><br>Destinations we assist with: ' + AGENT_DATA.packageDestinations.join(', ') + '.';
    html += '<p class="ptv-note">Exact itinerary and pricing depend on your dates, vehicle and group size — confirmed on WhatsApp.</p>';
    addBotMessage(html);
    addButtons([
      { label: '📝 Start Package Enquiry', onClick: function () {
          startSimpleEnquiry('J&K Tour Package', { noteQuestion: 'Which destinations are you interested in?' });
        } },
      { label: '⬅ Main Menu', onClick: renderMainMenu },
    ]);
  }

  function renderVehicles() {
    var html = '<strong>Vehicles Available</strong><ul class="ptv-list">';
    AGENT_DATA.vehicles.forEach(function (v) { html += '<li><strong>' + v.name + '</strong> — ' + v.desc + '</li>'; });
    html += '</ul><p class="ptv-note">Fares depend on route, season and availability — call or WhatsApp for the current fare, we don\'t publish fixed prices.</p>';
    addBotMessage(html);
    addButtons([
      { label: '📝 Ask About a Vehicle', onClick: function () {
          startSimpleEnquiry('Vehicle Enquiry', { noteQuestion: 'Which vehicle, and for which route?' });
        } },
      { label: '⬅ Main Menu', onClick: renderMainMenu },
    ]);
  }

  // ---------------------------------------------------------------
  // FAQs + free-text keyword fallback (still fully rule-based —
  // simple keyword matching only, no AI/LLM call of any kind)
  // ---------------------------------------------------------------
  function renderFaqMenu() {
    addBotMessage('Pick a question, or type your own below:');
    var opts = AGENT_DATA.faqs.map(function (f) {
      return { label: f.q, onClick: function () { addBotMessage(f.a); backToFaqOrMenu(); } };
    });
    addButtons(opts);
    addInput({
      placeholder: 'Type a question…',
      onSubmit: function (text) { handleFreeText(text); }
    });
    backToMenuButton();
  }

  function backToFaqOrMenu() {
    addButtons([
      { label: '❓ Another Question', onClick: renderFaqMenu },
      { label: '⬅ Main Menu', onClick: renderMainMenu },
    ]);
  }

  function handleFreeText(text) {
    var t = text.toLowerCase();
    // 1) try matching an FAQ by keyword overlap
    var best = null, bestScore = 0;
    AGENT_DATA.faqs.forEach(function (f) {
      var score = keywordScore(t, f.q.toLowerCase());
      if (score > bestScore) { bestScore = score; best = f; }
    });
    // 2) try matching a route by keyword (e.g. "katra", "srinagar")
    var routeMatch = AGENT_DATA.routes.find(function (r) {
      return t.indexOf(r.id.split('-')[0]) !== -1 || t.indexOf(r.label.toLowerCase().split(' ')[0]) !== -1;
    });

    if (bestScore >= 2) {
      addBotMessage(best.a);
      backToFaqOrMenu();
    } else if (routeMatch) {
      renderRouteInfo(routeMatch);
    } else {
      addBotMessage('I can help with taxi bookings, sightseeing, hotels, vehicles and tour enquiries. For anything else, please continue on WhatsApp.');
      whatsAppFallback('Hello Patnitop Travels Hub, I have a question: ' + text);
      backToMenuButton();
    }
  }

  function keywordScore(input, question) {
    var stop = { 'the': 1, 'a': 1, 'is': 1, 'do': 1, 'you': 1, 'to': 1, 'for': 1, 'i': 1, 'my': 1, 'and': 1, 'of': 1, 'in': 1 };
    var words = input.split(/\W+/).filter(function (w) { return w.length > 2 && !stop[w]; });
    var score = 0;
    words.forEach(function (w) { if (question.indexOf(w) !== -1) score++; });
    return score;
  }

})();
